import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
    {
        path: '/',
        redirect: '/home',
    },
    {
        path: '/login',
        name: 'Login',
        component: () => import('@/views/Login/index.vue'),
        meta: {
            title: '登录',
            requiresAuth: false,
        },
    },
    {
        path: '/layout',
        name: 'Layout',
        component: () => import('@/Layout/index.vue'),
        redirect: '/home',
        meta: {
            requiresAuth: true,
        },
        children: [
            {
                path: '/home',
                name: 'Home',
                component: () => import('@/views/Home/index.vue'),
                meta: {
                    title: '首页',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '首页',
                    menuIcon: 'home',
                    menuOrder: 1,
                },
            },
            // {
            //     path: '/users',
            //     name: 'UserList',
            //     component: () => import('@/views/UserList/index.vue'),
            //     meta: {
            //         title: '用户列表',
            //         requiresAuth: true,
            //     },
            // },
            {
                path: '/user-manage',
                name: 'UserManage',
                component: () => import('@/views/UserManage/index.vue'),
                meta: {
                    title: '用户管理',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '用户管理',
                    menuIcon: 'user',
                    permissionCode: 'user.view_user',
                    menuOrder: 7,
                },
            },
            // {
            //     path: '/roles',
            //     name: 'RoleList',
            //     component: () => import('@/views/RoleList/index.vue'),
            //     meta: {
            //         title: '角色列表',
            //         requiresAuth: true,
            //     },
            // },
            {
                path: '/role-manage',
                name: 'RoleManage',
                component: () => import('@/views/RoleManage/index.vue'),
                meta: {
                    title: '角色管理',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '角色管理',
                    menuIcon: 'team',
                    permissionCode: 'user.view_role',
                    menuOrder: 8,
                },
            },
            // {
            //     path: '/permissions',
            //     name: 'PermissionList',
            //     component: () => import('@/views/PermissionList/index.vue'),
            //     meta: {
            //         title: '权限列表',
            //         requiresAuth: true,
            //     },
            // },
            {
                path: '/permission-manage',
                name: 'PermissionManage',
                component: () => import('@/views/PermissionManage/index.vue'),
                meta: {
                    title: '权限管理',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '权限管理',
                    menuIcon: 'safety',
                    permissionCode: 'user.view_permission',
                    menuOrder: 9,
                },
            },
            {
                path: '/chat-center',
                name: 'ChatCenter',
                component: () => import('@/views/Chat/index.vue'),
                meta: {
                    title: '聊天室',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '聊天室',
                    menuIcon: 'chat',
                    permissionCode: 'user.view_user',
                    menuOrder: 6,
                },
            },
            {
                path: '/ws-test',
                redirect: '/chat-center',
                meta: {
                    requiresAuth: true,
                },
            },
            {
                path: '/settings',
                name: 'Settings',
                component: () => import('@/views/Settings/index.vue'),
                meta: {
                    title: '设置',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '设置',
                    menuIcon: 'tool',
                    menuOrder: 11,
                },
            },
            {
                path: '/profile-center',
                name: 'ProfileCenter',
                component: () => import('@/views/Profile/index.vue'),
                meta: {
                    title: '个人中心',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '个人中心',
                    menuIcon: 'user',
                    menuOrder: 10,
                },
            },
            {
                path: '/file-manage',
                name: 'FileManage',
                component: () => import('@/views/FileManage/index.vue'),
                meta: {
                    title: '文件管理',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '文件管理',
                    menuIcon: 'file',
                    permissionCode: 'user.view_user',
                    menuOrder: 2,
                },
            },
            {
                path: '/upload-center',
                name: 'UploadCenter',
                component: () => import('@/views/Upload/index.vue'),
                meta: {
                    title: '上传任务',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '上传任务',
                    menuIcon: 'upload',
                    permissionCode: 'user.view_user',
                    menuOrder: 3,
                },
            },
            {
                path: '/entertainment',
                name: 'Entertainment',
                component: () => import('@/views/Entertainment/index.vue'),
                redirect: '/entertainment/game',
                meta: {
                    title: '娱乐中心',
                    requiresAuth: true,
                    menu: true,
                    menuTitle: '娱乐中心',
                    menuIcon: 'trophy',
                    menuOrder: 4,
                },
                children: [
                    {
                        path: 'game',
                        name: 'EntertainmentGame',
                        component: () => import('@/views/Entertainment/Game/index.vue'),
                        redirect: '/entertainment/game/2048',
                        meta: {
                            title: '游戏',
                            requiresAuth: true,
                            menu: true,
                            menuTitle: '游戏',
                            menuIcon: 'appstore',
                            menuOrder: 1,
                        },
                        children: [
                            {
                                path: '2048',
                                name: 'EntertainmentGame2048',
                                component: () => import('@/views/Entertainment/Game/Game2048View.vue'),
                                meta: {
                                    title: '2048',
                                    requiresAuth: true,
                                    menu: true,
                                    menuTitle: '2048',
                                    menuIcon: 'trophy',
                                    menuOrder: 1,
                                },
                            },
                        ],
                    },
                    {
                        path: 'music',
                        name: 'EntertainmentMusic',
                        component: () => import('@/views/Entertainment/Music/index.vue'),
                        meta: {
                            title: '音乐',
                            requiresAuth: true,
                            menu: true,
                            menuTitle: '音乐',
                            menuIcon: 'music',
                            menuOrder: 2,
                        },
                    },
                ],
            },
        ],
    },
    {
        path: '/404',
        component: () => import('@/views/Error/index.vue'),
    },
    {
        path: '/:pathMatch(.*)*',
        redirect: '/404',
    },
]
